# Generated by Django 5.0.3 on 2024-06-13 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_age'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
