# Generated by Django 5.0.3 on 2024-05-12 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_songs_listened'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='songs',
            options={'ordering': ['id']},
        ),
    ]
