# Generated by Django 5.0.3 on 2024-05-12 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_artist_number_of_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='number_of_members',
        ),
    ]
