# Generated by Django 5.0.3 on 2024-05-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_remove_artist_number_of_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='member',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='search',
            field=models.IntegerField(default=0),
        ),
    ]
