# Generated by Django 5.0.3 on 2024-05-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_artist_member_artist_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='albom',
            name='songs_count',
            field=models.IntegerField(default=0),
        ),
    ]
